apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qgegztr8t-nodejs 
  janus-idp.io/tekton: qgegztr8t-nodejs
  backstage.io/kubernetes-id: qgegztr8t-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qgegztr8t-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml